version: "3.7"

services:
  application:
    image: ${IMAGE}:${VERSION}
    networks:
      - overlay
    ports:
      - "8080:8080"
    volumes:
      - application:/app/private
    environment:
      - GIN_MODE=release
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=mongodb://${DB_USERNAME}:${DB_PASSWORD}@db-mongo:27017
      
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M

    depends_on:
      - db-mongo
      
  db-mongo:
    image: mongo:latest
    networks:
      - overlay
    ports:
      - "27017:27017"
    volumes:
      - db-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 1024M

volumes:
  application:
  db-mongo:

networks:
  overlay:
    driver: overlay
