version: "3.7"

services:
  db-postgres:
    image: registry.cn-hangzhou.aliyuncs.com/jrjr/postgres:16.3-alpine3.20
    networks:
      - overlay
    # ports:
    #   - "10001:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    environment:
      - PGTZ=${TIMEZONE}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "2.00"
          memory: 4096M
        reservations:
          cpus: "1.00"
          memory: 2048M

  mid-redis:
    image: registry.cn-hangzhou.aliyuncs.com/jrjr/redis:7.2.5-alpine3.20
    networks:
      - overlay
    # ports:
    #   - "10002:6379"
    volumes:
      - mid-redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.00"
          memory: 4096M
        reservations:
          cpus: "0.50"
          memory: 2048M

  application:
    image: ${IMAGE}:${VERSION}
    networks:
      - overlay
    ports:
      - "10000:8080"
    volumes:
      - application:/app/private
    environment:
      - GIN_MODE=release
      - IMAGE=${IMAGE}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URI=redis://default:${REDIS_PASSWORD}@mid-redis:6379
      - POSTGRES_URI=postgres://${PG_USERNAME}:${PG_PASSWORD}@db-postgres:5432/${PG_USERNAME}?sslmode=disable

    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M

    depends_on:
      - db-postgres
      - mid-redis

volumes:
  application:
  mid-redis:
  db-postgres:

networks:
  overlay:
    driver: overlay
