version: "3.7"

services:
  # db-mongo:
  #   image: registry.cn-hangzhou.aliyuncs.com/jrjr/mongo:7.0.12
  #   networks:
  #     - overlay
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - db-mongo:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: "2.00"
  #         memory: 4096M
  #       reservations:
  #         cpus: "1.00"
  #         memory: 2048M

  db-postgres:
    image: registry.cn-hangzhou.aliyuncs.com/jrjr/postgres:16.3-alpine3.20
    networks:
      - overlay
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    environment:
      - PGTZ=$(TIMEZONE)
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}

    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "2.00"
          memory: 4096M
        reservations:
          cpus: "1.00"
          memory: 2048M

  mid-redis:
    image: registry.cn-hangzhou.aliyuncs.com/jrjr/redis:7.2.5-alpine3.20
    networks:
      - overlay
    ports:
      - "6379:6379"
    volumes:
      - mid-redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.00"
          memory: 4096M
        reservations:
          cpus: "0.50"
          memory: 2048M

  # mid-rabbit:
  #   image: rabbitmq:alpine
  #   networks:
  #     - overlay
  #   ports:
  #     - "5672:5672"
  #   volumes:
  #     - mid-rabbit:/var/lib/rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_VHOST=rabbit_vhost
  #     - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
  #     - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}

  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '1.00'
  #         memory: 2048M
  #       reservations:
  #         cpus: '0.50'
  #         memory: 1024M

  application:
    image: ${IMAGE}:${VERSION}
    networks:
      - overlay
    ports:
      - "80:8080"
    volumes:
      - application:/app/private
    environment:
      - GIN_MODE=release
      - IMAGE=${IMAGE}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URI=redis://default:${REDIS_PASSWORD}@mid-redis:6379
      # - RABBIT_URI=amqp://${RABBIT_USERNAME}:${RABBIT_PASSWORD}@mid-rabbit:5672
      # - MONGODB_URI=mongodb://${DB_USERNAME}:${DB_PASSWORD}@db-mongo:27017
      - POSTGRES_URL=postgres://${PG_USERNAME}:${PG_PASSWORD}@db-postgres:5432/${PG_USERNAME}?sslmode=disable

    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M

    depends_on:
      # - db-mongo
      - db-postgres
      - mid-redis
      # - mid-rabbit

volumes:
  application:
  mid-redis:
  # mid-rabbit:
  # db-mongo:
  db-postgres:
    # driver: local

networks:
  overlay:
    driver: overlay
